######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Mon Jun 14 11:11:32 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
