######################################################################
#
# File name : cpu_tb_simulate.do
# Created on: Mon Jun 14 11:11:32 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.cpu_tb xil_defaultlib.glbl

do {cpu_tb_wave.do}

view wave
view structure
view signals

log -r /*

do {cpu_tb.udo}

run 120000ns
