######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Mon Jun 14 11:11:21 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib work
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib msim

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../cpu_31.srcs/sources_1/new/pcreg.v" \
"../../../cpu_31.srcs/sources_1/new/regfile.v" \
"../../../cpu_31.srcs/sources_1/new/MUX_5bit.v" \
"../../../cpu_31.srcs/sources_1/new/S_Ext18.v" \
"../../../cpu_31.srcs/sources_1/new/S_Ext16.v" \
"../../../cpu_31.srcs/sources_1/new/MUX.v" \
"../../../cpu_31.srcs/sources_1/new/Ext5.v" \
"../../../cpu_31.srcs/sources_1/new/Ext16.v" \
"../../../cpu_31.srcs/sources_1/new/alu.v" \

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../cpu_31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../cpu_31.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../cpu_31.srcs/sources_1/new/Dram.v" \
"../../../cpu_31.srcs/sources_1/new/cpu.v" \
"../../../cpu_31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../cpu_31.srcs/sim_1/new/cpu_tb.v" \

# compile glbl module
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

