# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath E:/ModelSimPE/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/computer_composition/MIPS54/cpu_54/cpu_54.cache/wt [current_project]
set_property parent.project_path D:/computer_composition/MIPS54/cpu_54/cpu_54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/coe/32_clz.hex.coe
add_files D:/coe/mips_31_mars_simulate.coe
add_files D:/coe/35_jalr.hex.coe
add_files D:/coe/37_lbu.hex.coe
add_files D:/coe/36.39_lbsb.hex.coe
add_files D:/coe/36.39_lbsb2.hex.coe
add_files D:/coe/37_lbu2.hex.coe
add_files D:/coe/38_lhu.hex.coe
add_files D:/coe/38_lhu2.hex.coe
add_files D:/coe/40.41_lhsh.hex.coe
add_files D:/coe/40.41_lhsh2.hex.coe
add_files D:/coe/42.45_mfc0mtc0.hex.coe
add_files D:/coe/43.46_mfhi.mthi.hex.coe
add_files D:/coe/44.47_mflo.mtlo.hex.coe
add_files D:/coe/48_mult.hex.coe
add_files D:/coe/49_multu.hex.coe
add_files D:/coe/54_div.hex.coe
add_files D:/coe/33_divu.hex.coe
add_files c:/Users/C.X/Desktop/mips_54_mars_simulate_student_ForWeb.coe
add_files -quiet D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen.dcp
set_property used_in_implementation false [get_files D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen.dcp]
read_verilog -library xil_defaultlib {
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/CP0.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/S_Ext8.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/Ext8.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/CLZ.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/DIVU.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/DIV.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/multu.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/MULT.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/MUX8.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/S_Ext18.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/S_Ext16.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/regfile.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/pcreg.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/MUX_5bit.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/MUX.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/Ext5.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/alu.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/Ext16.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/seg7x16.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/cpu.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/Dram.v
  D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/constrs_1/new/icf.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
