# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen.xci
# IP: The module: 'imen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen.xci
# IP: The module: 'imen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/computer_composition/MIPS54/cpu_54/cpu_54.srcs/sources_1/ip/imen/imen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
