######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Sat Jul 10 11:21:22 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
