######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Sat Jul 10 12:39:18 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib work
E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib msim

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\ModelSimPE\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"cpu_tb_time_synth.v" \
"../../../../cpu_54.srcs/sim_1/new/cpu_tb.v" \


quit -force

