######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Thu Jul 08 21:23:57 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
